package ShopPackage;

public enum Command {
    PRODUCT_ADD,
    PRODUCT_INCREASE,
    PRODUCT_DECREASE,
    PRODUCT_PRICE,
    PRODUCT_INFO,
    PRODUCT_DELETE,
    GROUP_CREATE,
    GROUP_NAME_CHANGE,
    ANSWER_OK;
}

